Bugfix/optimize likelihood
GTJuniorDesign0100-2020/anti-malarial-MCMC-bayesian-algorithm pull request #45
Opened 2020-11-12 02:00 UTC by JHDeerin

Improved `likelihood_ratios` calculation by ~600% (by eliminating a for loop + using a more optimized version of `nanmeans`). Since `likelihood_ratios` previously took up ~15% of the total runtime, this should improve overall algorithm performance by about 12.5%.

Adds 1 new Python dependency, a library called [bottleneck](https://bottleneck.readthedocs.io/en/latest/).

2020-11-18 01:02 UTC, MultiDream commented
Reviewed the merge request. Seems like the rewrite was a good way to avoid a for loop, but it doesn't pass all tests.
Assertion error for tests on line 204. Looks like the output doesn't match expectations.

Only one thing I'd note:
There is a reshaping left up to numpy to resolve on runtime. This may have some unexpected consequences if the shape of num_ids is not quite what you expect. That being said, I can't see any reason that would be an issue at this time, so if you feel comfortable with it, don't worry about it. Might be related to the issue, might not be.

2020-11-18 02:52 UTC, JHDeerin commented
I believe the failing test is an [xfail test](https://docs.pytest.org/en/reorganize-docs/new-docs/user/xfail.html), not an actual failure; the reshape is actually unnecessary and should be removed with the latest commit.

2020-11-19 05:01 UTC, danewrye requested changes
Code looks great, just a couple of extremely minor comment questions. 

When tested, it did not run into any failed tests for me.

2020-11-19 05:01 UTC, danewrye commented on api/algorithm_site_instance.py
> +        # alldistance = ids, loci, max_moi**2
Is this code unused, and can now be deleted?

2020-11-19 05:01 UTC, danewrye commented on api/algorithm_site_instance.py
> +                        # all_recrf = ids, loci, max_moi**2
Same comment as above: this looks like code that has been commented out and can now be deleted.

2020-11-19 05:01 UTC, danewrye commented on README.md
> +pip install bottleneck
Cool library! Optimizing the optimized

2020-11-19 15:53 UTC, JHDeerin commented on api/algorithm_site_instance.py
> +        # alldistance = ids, loci, max_moi**2
This code should already be deleted on the latest commit; I think you reviewed one of the earlier commits accidentally?

2020-11-19 16:08 UTC, danewrye commented on api/algorithm_site_instance.py
> +        # alldistance = ids, loci, max_moi**2
Apologies, I will approve then. Everything else looks good.

2020-11-19 16:08 UTC, danewrye approved these changes

2020-11-19 16:25 UTC, merged