Integration test
GTJuniorDesign0100-2020/anti-malarial-MCMC-bayesian-algorithm pull request #55
Opened 2020-11-17 20:14 UTC by HeatherMikan

2020-11-17 23:03 UTC, JHDeerin requested changes
The changes look good, everything seems to run correctly on my end, and the output CSVs are MASSIVELY more readable!

Content-wise everything is fine; there are small places where I think the code could be cleaned up or made more clear that I've marked (you tend to use a lot of short variable names that could be made more explicit, and there were a few places where comments were missing). Patch those and this is ready to merge.

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
>          '''
Add a brief comment here describing what the `site_names` input is , `:param site_names: ...`

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
> +    def __init__(self, site_names):
Add a type hint for the arg, i.e. `site_names: List[str]`

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
> +        for site in self.site_sample_ids:
Use `self.site_ids` instead, since it's clearer and the `site_sample_ids` keys aren't in a guaranteed order? (shouldn't matter in this case, but might as well be consistent)

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
> +            loci1 = ['q', 'd']
These should both be `'N/A'`, since they're technically not loci (and the row description already describes what q/d mean)

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
> +        for site in self.site_sample_ids:
Counter-argument is that this currently handles if the key ever changes to not be the site name, but then the variable name would have to change anyway, so I still think the change should be done

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
>          for site_name, summary_df in self.run_summary_stat_dfs.items():
Should probably still use `self.site_names` here, but that'd require a double for-loop and it wouldn't change the outcome...so if you think this is cleaner as-is, it should be safe to leave it

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
> +        new_col = []
Could you rename these 2 to be a bit clearer? What's the `data` used for? What kind of new column?

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
> +        desc = []
Rename to `row_descriptions`, just to be clear?

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
> +                desc.append("Average Simpson's Index")
Could you leave a comment mentioning that this is initialization logic, and why it's inside the for loop? I was confused for a bit why this was here until I realized you needed access to one of the summary dfs to get the number of loci.

On second thought, it we're assuming all the sites have the same number of loci anyway, can you find a way to do this initialization before the for loop, if possible (e.g. grabbing `run_summary_stat_dfs.values[0]`)?

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
> +            locus_names = list(summary_df.index.values[0:-1])
What's the difference between `loci` and `locus_names`? Can you get one from the other instead, or, if they are different, make that clear via the variable names?

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
> +                desc = desc[0:-1]
Could you leave a comment describing what this is doing/checking for in the output CSV?

2020-11-17 23:03 UTC, JHDeerin commented on api/algorithm_instance.py
> +            new_col = []
Could you give `res`/`new_col` more descriptive names?

2020-11-17 23:03 UTC, JHDeerin commented on integration_test.py
> +    ittr = int(argv[0])
Is this the number of runs? If so, could you rename it to `num_runs` or something (since ittr makes it sound like it's the number of `iterations` for each run)?

2020-11-17 23:03 UTC, JHDeerin commented on integration_test.py
> +    results_writter = csv.writer(results)
Could you leave a docstring comment or a comment at the top of the file explaining what this does, how to run it, and what it outputs/how to interpret the output (if not self explanatory)?

Explaining how to run it is especially important.

2020-11-17 23:03 UTC, JHDeerin commented on integration_test.py
> +        retP = subprocess.call(["python3", "anti-malarial-MCMC-bayesian-algorithm/main.py"])
Are these 2 ever used? If not, delete them? If they are, why is the R script commented out?

2020-11-17 23:03 UTC, JHDeerin commented on integration_test.py
> +def get_por(t):
What does this function do? Rename it to 'get_probability_of_recrudescence_file', or something close to its job (I'm not sure what this function actually does, and why it's returning a list instead of a file)

2020-11-17 23:03 UTC, JHDeerin commented on integration_test.py
> +def get_mc(t):
Ditto; same as for `get_por`, give this a more explicit name?

2020-11-17 23:03 UTC, JHDeerin commented on integration_test.py
> +#    print(r_conv)
Delete

2020-11-17 23:03 UTC, JHDeerin commented on integration_test.py
> +    results_writter = csv.writer(results)
Typo; rename to `results_writer`

2020-11-17 23:03 UTC, JHDeerin commented on integration_test.py
> +    for x in range(len(sum_p[1])):
What's x? Give this a clearer name?

2020-11-17 23:03 UTC, JHDeerin commented on integration_test.py
> +    for x in range(len(sum_r[1])):
Ditto; what's `x` What is this for loop calculating? Similarly, what's `fl`?

2020-11-17 23:03 UTC, JHDeerin commented on integration_test.py
> +    res = {'Num Samples':0, 'Num Itterations': 0, 'Total Compairisons':0, 'Similarities':0, 'Differences':0, 'Percent Correct':0}
2 typos: `Num Itterations` -> `Num Iterations`, `Total Compairisons` -> `Total Comparisons`

2020-11-17 23:03 UTC, JHDeerin commented on integration_test_results.csv
> +39,75,190,179,11,0.942105263,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Delete this file (and possibly add `*.csv` to the `.gitignore`?); we can regenerate it any time and it'll change each run, which is a hassle on Git. If we want to share the results with Mat, we can always send it to him manually.

2020-11-17 23:03 UTC, JHDeerin commented on integration_test_results_sum.csv
> +,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Ditto; delete this CSV since we can always regenerate it

2020-11-19 02:10 UTC, HeatherMikan commented on api/algorithm_instance.py
> +        for site in self.site_sample_ids:
I tried making this change but I needed extended_ids to be a dictionary with sites as keys (in line 100). I couldn't find a way around this issue.

2020-11-19 16:36 UTC, JHDeerin commented on api/algorithm_instance.py
> +        for site in self.site_sample_ids:
Okay, that's alright; this is still decently clear

2020-11-19 17:04 UTC, JHDeerin approved these changes
All of these changes are good and helpful, and I think this is ready to merge! There's some minor clarity things still, but at this point I think it's important to merge stuff in; if you can fix the highlighted stuff in 5 minutes, great, but otherwise I'm okay with merging it in now.

2020-11-19 17:04 UTC, JHDeerin commented on api/algorithm_instance.py
> +        num_loci = int(len(loci_names)/2)
A bit confusing why this is divided by 2 (maybe leave a comment?), but not a huge issue

2020-11-19 17:04 UTC, JHDeerin commented on api/algorithm_instance.py
> +        del loci_names[-1]
What is this deleting? Why does it need to be deleted? Leave a comment?

2020-11-19 17:04 UTC, JHDeerin commented on integration_test.py
> +def get_probability_of_recrudescence_file(t):
Minor, but having a parameter just called "t" and having to arbitrarily know to pass in "p" or "r" to get the right result is a bit confusing; especially since it's binary, it probably makes more sense to make this argument a boolean instead, like `is_python_output`, and then just make it an `if...else...` statement instead of 2 separate `ifs`.

Since the method is so short and what it does is clear after reading the "UPDATE HERE" comment, though, I think this is acceptable. But in general, having to read through a function's implementation to know how to use it is a red flag.

2020-11-19 17:04 UTC, JHDeerin commented on integration_test.py
> +1000 iterations), so for example running with 'python integration_test.py 5'
Mention that in order to change the number of iterations per run, you actually have to change the `main.py` and `main.r` files (i.e. the 1000 iterations isn't defined anywhere in this file itself - that confused me for a second).

Also, somewhere in this comment, possibly give a copy-pasteable example of running this from the command line? e.g.:

```
python integration_test.py 5
```

2020-11-23 03:58 UTC, JHDeerin approved these changes
Looks good; I can merge it!

2020-11-23 04:21 UTC, merged